## 2048

- [x] print board
- [x] input keystroke
- [x] new number in board
- [x] move
- [ ] check if 2048
- [ ] reached end?
- [ ] crasg on invalid input


In [12]:
import numpy as np

In [3]:
# board = np.asarray?

In [3]:
board = np.asarray

In [37]:
board = np.asarray([[-1 for _ in np.arange(4)] for _ in np.arange(4)])

def print_board(b):
    for i in np.arange(4):
        for j in np.arange(4):
            val = b[i][j]
            if val == -1:
                print 'x',
            else:
                print b[i][j],
        print 
        
print_board(board)

x x x x
x x x x
x x x x
x x x x


## input keystroke

In [15]:
from getkey import getkey, keys
print keys.code(keys.UP)

print keys.name('\xe0H')
# key = getkey()
# print('You entered ')
# print(key)

None
UP


## new number on board

In [27]:
def add_new_number(board):
    prob = np.random.random_sample()
    new_val = -1
    if prob < 0.4:
        new_val = 4
    else:
        new_val = 2
    while(True):
        row = np.random.randint(0, 4)
        col = np.random.randint(0, 4)
        if board[row][col] == -1:
            board[row][col] = new_val
            break
    return board

for _ in np.arange(3):
# print_board(board)
    add_new_number(board)
    print_board(board)
    print("***********************************")

    

x x x x
2 x x x
x x x x
x x x x
***********************************
x x x x
2 x x x
x 2 x x
x x x x
***********************************
x x x x
2 x x x
x 2 x 2
x x x x
***********************************


## move

In [28]:
def move_up(board):
    # change values in destination rows
    # no changes in last row
    for row in (0, 1, 2):
        for col in np.arange(4):
            cur_val = board[row][col]
            neighbour_row = row+1
            neighbour = board[neighbour_row][col]
            if cur_val == -1:
                board[row][col] = neighbour
            else:
                if cur_val == neighbour:
                    board[row][col] = cur_val * 2
                else:
    
    for row in (0, 1, 2):
        for val, col in enumerate(board[row]):
            if val != -1:
                if val == board[row+1][col]:
                    board[row][col] == board[row][col] + board[row+1][col]
    return board


def move_down(board):
    # change values in destination rows
    # no changes in first row
    for row in (1, 2, 3):
        for val, col in enumerate(board[row]):
            if val != -1:
                if val == board[row-1][col]:
                    board[row][col] == board[row][col] + board[row-1][col]
    return board

def move_left(board):
    # change values in destination cols
    # no changes in last col
    for col in (0, 1, 2):
        for val, row in enumerate(board[:, col]):
            if val != -1:
                if val == board[row][col+1]:
                    board[row][col] == board[row][col] + board[row][col+1]
    return board

def move_right(board):
    # change values in destination cols
    # no changes in first col
    for col in (1, 2, 3):
        for val, row in enumerate(board[:, col]):
            if val != -1:
                if val == board[row][col-1]:
                    board[row][col] == board[row][col] + board[row][col-1]
    return board


    


## is 2048?

In [29]:
import pygame

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html


In [38]:
arr = [2, -1, 2, -1]

In [33]:
x = np.arange(9.).reshape(3, 3)

In [34]:
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [41]:
x[x>5]

array([6., 7., 8.])

In [42]:
arr

[2, -1, 2, -1]

In [45]:
arr[arr<0]

2

In [50]:
arr = np.asarray([2, -1, 4, -1])

In [51]:
arr

array([ 2, -1,  4, -1])

In [52]:
arr[arr!=-1]

array([2, 4])

In [54]:
arr.size?

In [55]:
arr

array([ 2, -1,  4, -1])

In [62]:
arr2 = np.asarray([89, 44])

In [63]:
arr2

array([89, 44])

In [64]:
arr[:2] = arr2[:]
arr

array([89, 44,  4, -1])

In [65]:
arr[2:] = 0
arr

array([89, 44,  0,  0])

In [66]:
board

array([[-1, -1, -1, -1],
       [ 2, -1, -1, -1],
       [-1,  2, -1,  2],
       [-1, -1, -1, -1]])

In [68]:
for r, i in enumerate(arr):
    print r, i

0 89
1 44
2 0
3 0


In [5]:
board

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [16]:
def shift_to_front(arr):
    arr = np.asarray(arr)
    all_ele = arr[arr!=-1]
    count = all_ele.size
    arr[:count] = all_ele[:]
    arr[count:] = -1
    print arr
    

In [ ]:
def move_left(board):
    

In [17]:

a1 = [-1, 2, 2, -1]
shift_to_front(a1)

[ 2  2 -1 -1]


In [18]:
shift_to_front([2, -1, 4, -1])

[ 2  4 -1 -1]


In [19]:
shift_to_front([2, 2, -1, -1])

[ 2  2 -1 -1]


In [20]:
shift_to_front([2, -1, 2, -1])

[ 2  2 -1 -1]


In [21]:
shift_to_front([-1, -1, 2, 2])

[ 2  2 -1 -1]


In [25]:
def _shift_and_merge(arr): # [2 2 2 2]
#     print "*******************"
#     print arr
    arr = np.asarray(arr)
    result = np.copy(arr)
    
    # shift
    all_ele = arr[arr!=-1]
    count = all_ele.size
    if count != arr.size:
        result[:count] = all_ele[:]
        result[count:] = -1
#     print("After shifting")    
#     print result

    # merge [2 2 2 2]
    for index, ele in enumerate(result[:-1]):
        if ele == result[index + 1] and ele != -1:
#             print result
            result[index] = ele * 2            
            result[index + 1] = -1
#             print result
            result[(index + 1):] = _shift_and_merge(result[(index + 1):])

    return result

In [26]:
_shift_and_merge([2, 2, -1, -1])

array([ 4, -1, -1, -1])

In [27]:
_shift_and_merge([2, -1, -1, -1])

array([ 2, -1, -1, -1])

In [28]:
_shift_and_merge([-1, -1, -1, -1])

array([-1, -1, -1, -1])

In [29]:
_shift_and_merge([2, -1, 2, -1])

array([ 4, -1, -1, -1])

In [30]:
_shift_and_merge([-1, 2, 2, -1])

array([ 4, -1, -1, -1])

In [31]:
_shift_and_merge([-1, -1, 2, 2])

array([ 4, -1, -1, -1])

In [32]:
a

array([ 2,  2, -1, -1])

In [35]:
a[::-1]

array([-1, -1,  2,  2])

In [38]:
board

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [40]:
for ri, r in enumerate(board):
    for ci, ele in enumerate(r):
        board[ri][ci] = ri + ci
        
board


array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [41]:
board = np.arange(16)
board

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
board = board.reshape(4, 4)

In [43]:
board

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
board[1, :]

array([4, 5, 6, 7])

In [48]:
board[:, 1]

array([ 1,  5,  9, 13])

In [50]:
for e in board.T:
    print e

[ 0  4  8 12]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]


In [51]:
board

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
board.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [53]:
-1 in board

False

In [54]:
11 in board

True

In [61]:
class game_2048:
    pass

In [63]:
game_2048()

<__main__.game_2048 instance at 0x00000000074C78C8>

In [2]:
import numpy as np

In [4]:
np.ones(5, 5 )

TypeError: data type not understood

In [6]:
a=[1, 2, 3, 4]

In [9]:
b = a[4:]

In [10]:
b

[]

In [11]:
a[4]

IndexError: list index out of range

In [6]:
BLACK        = (0, 0, 0)
GREEN        = (  0, 155,   0)
BLUE         = (  0,   0, 155)


import pygame

In [4]:
display_surf = pygame.display.set_mode((400, 400))

In [3]:
pygame.init()
FONT = pygame.font.Font(pygame.font.match_font('calibri'), 16)

FONT.set_bold(True)

In [7]:
pygame.display.set_caption('2048')
text_surf = FONT.render('Can you reach 2048?', True, GREEN, BLACK)
text_rect = text_surf.get_rect()
text_rect.centerx = 200
text_rect.centery = 50
        # text_rect.topleft = (10, 10)
display_surf.blit(text_surf, text_rect)

<rect(122, 42, 156, 17)>

In [9]:
display_surf.subsurface?

Docstring:
subsurface(Rect) -> Surface
create a new surface that references its parent
Type:      builtin_function_or_method
